### PR TITLE
clean up checking closed window

### PR DESCRIPTION
**Pull request by beeman**
Hey @JacobDoucet , just watched your video on YouTube, nice stuff you do with the URL state.

I figured you were probably interested in a cleaner way to listen to the window closing :)

### CODE REVIEW

**Comment by JacobDoucet** [comment]
> Hey @JacobDoucet , just watched your video on YouTube, nice stuff you do with the URL state.
> 
> I figured you were probably interested in a cleaner way to listen to the window closing :)

Thanks for this! I've used `onbeforeunload` before, but had some consistency problems with it. I found that sometimes when the user clicks the close button on the Browser window itself, the handler doesn't fire. Have you run into this before? I'm going to give it a try, though!

**Comment by JacobDoucet** [comment]
@beeman Now that I think about it, maybe I was trying to do it with an event listener instead of attaching it right to the window object itself... I'm going to experiment with this once I'm finished work for the day.

**Comment by JacobDoucet** [comment]
This worked nicely, thanks! I had an issue with the text not changing, but realized this was due to change detection not running when the close button was clicked from the popup - so I added the ChangeDetectorRef, called detect changes in onbeforeunload. I'll include this in the next video!

**Comment by beeman** [comment]
Glad to hear that! Looking forward to the next video.

**Pull request merged**
